# Generated by Django 4.2.12 on 2024-10-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_personajes_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('operacion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('superficie_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superficie_cubierta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ambientes', models.IntegerField()),
                ('plantas', models.IntegerField()),
                ('dormitorios', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Personajes',
        ),
    ]
