# Generated by Django 4.2.12 on 2024-10-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_propiedad_delete_personajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
