# Generated by Django 4.2.12 on 2024-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_propiedad_nombre_alter_propiedad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='mapa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
