# Generated by Django 4.2.12 on 2024-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_propiedad_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='nombre',
            field=models.CharField(default='Casa', max_length=100),
        ),
    ]
